\documentclass{article}
\begin{document}

<<>>=
print(test_value)
@


<<test-main>>=
options(width = 60)
summary(iris)
@

Let's see how to work with child documents in knitr. Below we input
the file \textsf{theSub/ChildFile.Rnw}:

\Sexpr{knit_child('theSub/ChildFile.Rnw')}

<<>>=
d1_master <- read.csv('data/all_040_in_01.P1.csv')
head(d1_master)
@

<<>>=
d2_master <- read.csv('theSub/data/all_040_in_36.P1.csv')
head(d2_master)
@


Done!

\end{document}
