<<>>=
opts_knit$set(root.dir=normalizePath('../'))
@

\Sexpr{set_parent('master.Rnw')}
\Sexpr{opts_knit$set(self.contained=FALSE)}

This is the child doc.

<<>>=
print(test_value)
@


The working directory for the child is
<<child-wd>>=
getwd()
@

data from root
<<>>=
d1_child <- read.csv('data/all_040_in_01.P1.csv')
head(d1_child)
@

data from child
<<>>=
d2_child <- read.csv('theSub/data/all_040_in_36.P1.csv')
head(d2_child)
@

<<child_car_plot>>=
plot(cars)
@

